[package]
name = "ghe"
version = "0.1.0"
authors = ["Hirokazu Hata <h.hata.ai.t@gmail.com>"]

[dependencies]
quicli = { git = "https://github.com/killercup/quicli", branch = "master" }
diesel = { version = "1.3.2", features = ["sqlite"] }
diesel_migrations = "1.3.0"
graphql_client = { git = "https://github.com/tomhoule/graphql-client", branch = "master" }

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = { git = "https://github.com/seanmonstar/reqwest", branch = "master" }

dotenv = "0.13"
