[package]
name = "ghe"
version = "0.1.0"
authors = ["Hirokazu Hata <h.hata.ai.t@gmail.com>"]

[dependencies]
quicli = { git = "https://github.com/killercup/quicli", branch = "master" }
diesel = { version = "1.3.2", features = ["sqlite"] }
diesel_migrations = "1.3.0"
dotenv = "0.9.0"
github-gql-rs = "0.0.1"
serde_json = "1.0"

[patch.crates-io]
github-gql-rs = { path = "../github-rs/github-gql-rs" }
